import pandas as pd 
import numpy as np
datos=pd.read_csv('ATP.csv')
print(datos.info())
print(datos.head())
nuevo=pd.DataFrame(datos)
print(nuevo)
nuevo=nuevo.replace(np.nan,'0')
print("impresion sin nan")
print(nuevo.info())
print('\n')
print(nuevo.describe())
print('\n')
print("impresion solamente numeros")
print(nuevo.describe(include=[np.number]))
nuevo=nuevo.replace("N/A",0)
nuevo=nuevo.replace("NR",0)
print("lista de encabezados")
print(list(nuevo))
print(nuevo["WRank"])
nuevo["Wsets"]=nuevo["Wsets"].astype(int)
nuevo["WRank"]=nuevo["WRank"].astype(int)
print(nuevo.describe())
